import { Item } from './types';

/**
 * TODO ad musical instruments
 */

const ToolNames = [
  'alchemist-supplies',
  'brewer-supplies',
  'calligrapher-supplies',
  'carpenter-tools',
  'cartographer-tools',
  'cobbler-tools',
  'cook-utensils',
  'glassblower-tools',
  'jeweler-tools',
  'leatherworker-tools',
  'mason-tools',
  'painter-supplies',
  'potter-tools',
  'smith-tools',
  'tinker-tools',
  'weaver-tools',
  'woodcarver-tools',
  'disguise-kit',
  'forgery-kit',
  'dice-set',
  'dragonchess-set',
  'playing-card-set',
  'three-dragon-ante-set',
  'herbalism-kit',
  'navigator-tools',
  'poisoner-kit',
  'thieves-tools',
] as const;
type ToolNamesTuple = typeof ToolNames;
export type ToolName = ToolNamesTuple[number];

type ToolsType<T = unknown> = {
  [key in ToolName]: Item<T>;
};

export const tools: ToolsType = {
  'alchemist-supplies': {
    name: 'alchemist-supplies',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 50 },
    weight: 8,
  },
  'brewer-supplies': {
    name: 'brewer-supplies',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 20 },
    weight: 9,
  },
  'calligrapher-supplies': {
    name: 'calligrapher-supplies',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 10 },
    weight: 5,
  },
  'carpenter-tools': {
    name: 'carpenter-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 8 },
    weight: 6,
  },
  'cartographer-tools': {
    name: 'cartographer-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 15 },
    weight: 6,
  },
  'cobbler-tools': {
    name: 'cobbler-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 5 },
    weight: 5,
  },
  'cook-utensils': {
    name: 'cook-utensils',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 1 },
    weight: 8,
  },
  'glassblower-tools': {
    name: 'glassblower-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 30 },
    weight: 5,
  },
  'jeweler-tools': {
    name: 'jeweler-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 25 },
    weight: 2,
  },
  'leatherworker-tools': {
    name: 'leatherworker-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 5 },
    weight: 5,
  },
  'mason-tools': {
    name: 'mason-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 10 },
    weight: 8,
  },
  'painter-supplies': {
    name: 'painter-supplies',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 10 },
    weight: 5,
  },
  'potter-tools': {
    name: 'potter-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 10 },
    weight: 3,
  },
  'smith-tools': {
    name: 'smith-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 20 },
    weight: 8,
  },
  'tinker-tools': {
    name: 'tinker-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 50 },
    weight: 10,
  },
  'weaver-tools': {
    name: 'weaver-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 1 },
    weight: 5,
  },
  'woodcarver-tools': {
    name: 'woodcarver-tools',
    itemType: 'artisan-tools',
    description: '',
    cost: { gp: 1 },
    weight: 5,
  },
  'disguise-kit': {
    name: 'disguise-kit',
    itemType: 'tool',
    description: '',
    cost: { gp: 25 },
    weight: 3,
  },
  'forgery-kit': {
    name: 'forgery-kit',
    itemType: 'tool',
    description: '',
    cost: { gp: 15 },
    weight: 5,
  },
  'dice-set': {
    name: 'dice-set',
    itemType: 'gaming-set',
    description: '',
    cost: { sp: 1 },
    weight: 0,
  },
  'dragonchess-set': {
    name: 'dragonchess-set',
    itemType: 'gaming-set',
    description: '',
    cost: { gp: 1 },
    weight: 0.5,
  },
  'playing-card-set': {
    name: 'playing-card-set',
    itemType: 'gaming-set',
    description: '',
    cost: { sp: 5 },
    weight: 0,
  },
  'three-dragon-ante-set': {
    name: 'three-dragon-ante-set',
    itemType: 'gaming-set',
    description: '',
    cost: { gp: 1 },
    weight: 0,
  },
  'herbalism-kit': {
    name: 'herbalism-kit',
    itemType: 'tool',
    description: '',
    cost: { gp: 5 },
    weight: 3,
  },
  'navigator-tools': {
    name: 'navigator-tools',
    itemType: 'tool',
    description: '',
    cost: { gp: 25 },
    weight: 2,
  },
  'poisoner-kit': {
    name: 'poisoner-kit',
    itemType: 'tool',
    description: '',
    cost: { gp: 50 },
    weight: 2,
  },
  'thieves-tools': {
    name: 'thieves-tools',
    itemType: 'tool',
    description: '',
    cost: { gp: 25 },
    weight: 1,
  },
};
