name: dnd.js Unit Tests
run-name: ${{ github.actor }} is testing out dnd.js 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 18.x
      - name: Install node packages
        run: npm ci
      - name: Run unit tests
        run: npx jest
      
